services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
      - db_root_password
      - wp_admin_pass
      - wp_admin_user
      - wp_admin_email
    restart: on-failure
  
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
      - db_root_password
      - wp_admin_pass
      - wp_admin_user
    restart: on-failure

networks:
  inception:
    name: rtimsina_inception
    driver: bridge

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/ramesh/data/wordpress


  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/ramesh/data/mariadb

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt